### ISSUE TITLE
Peer-to-peer code reviews

### ISSUE THREAD

**Issue by Ferizad** [yusufobr/conference-capstone#1]
Kindly, work on button with id="collapse"
https://github.com/yusufobr/conference-capstone/blob/4f919a1051fb794dc7f0f0cf589a4de09f9c20aa/index.html#L244-L251
Add links to the nav menu
https://github.com/yusufobr/conference-capstone/blob/4f919a1051fb794dc7f0f0cf589a4de09f9c20aa/index.html#L60-L69

**Comment by yusufobr** [comment]
hey @Ferizad , 
Those notes have been taken into consideration and are now fixed.
